---
name: Semgrep

on:  # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Install packages
        run: |
          apk update
          apk upgrade
          apk add ca-certificates curl git

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify
        run: |
          chown -R root:root .
          echo "${{ vars.ALLOWED_SIGNERS }}" > "${HOME}/.signers"
          git -c gpg.ssh.allowedSignersFile="${HOME}/.signers" verify-commit HEAD

      - name: Download rules
        run: |
          curl \
            --fail \
            --proto =https \
            --capath /dev/null \
            --cacert /usr/share/ca-certificates/mozilla/Amazon_Root_CA_1.crt \
            --location \
            --max-redirs 1 \
            --output /rules.yml \
            https://semgrep.dev/c/r/all
            sha256sum /rules.yml

      - name: Scan
        run: |
          semgrep scan \
            --disable-version-check \
            --metrics=off \
            --error \
            --config=/rules.yml \
            --exclude-rule=dgryski.semgrep-go.readfull.io-readfull-n \
            --exclude-rule=dgryski.semgrep-go.errtodo.err-todo \
            .
